[package]
name = "phone-server"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.17.3"
dotenvy = "0.15.7"
futures-util = "0.3.32"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
